version: '3.4'

services:
  videostore.identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true
      - RunningInDocker=true
      - AZURE_TENANT_ID=${AZURE_TENANT_ID} # azure env variables must be used in order to connect to Azure KeyVault from docker container
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID} # add variables to windows environment variables or in VS solution .env file to be picked up by docker compose 
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    ports:
      - "8001:80"

  videostore.movies:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true 
      - RunningInDocker=true
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - OrderingApiBaseUrl=http://host.docker.internal:8003
    ports:
      - "8002:80"

  videostore.ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true
      - RunningInDocker=true
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    ports:
      - "8003:80"

